export default {
    Palette:{
        height: '97vh',
        width: '98.9vw',
        display: 'flex',
        flexDirection: 'column',
    },
    colors:{
        height: '90%',
    },
    goBack:{
        width: "20%",
        height: "50%",
        margin: "0 auto",
        display: "inline-block",
        position: "relative",
        cursor: "pointer",
        marginBottom: "-3.5px",
        backgroundColor : 'black',
        '& a':{
            color:'white' ,
            width : "100px",
            height: "30px",
            position: "absolute",
            display : "inline-block",
            top : "50%",
            left: "50%",
            marginLeft: "-50px",
            marginTop:" -15px",
            textAlign: "center",
            outline: "none",
            backgroundColor: 'rgba(255, 255, 255, 0.3)',
            fontSize: "1rem",
            lineHeight: "30px",
            textTransform: "uppercase",
            border: "none",
            cursor: "pointer",
            textDecoration: "none",
        },
    },
}

